//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClubClient.DbServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credential", Namespace="http://schemas.datacontract.org/2004/07/FitnessClub.DomainService.Models")]
    [System.SerializableAttribute()]
    public partial class Credential : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/FitnessClub.DomainService.Models")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/FitnessClub.DomainService.Models")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdminIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdminId {
            get {
                return this.AdminIdField;
            }
            set {
                if ((this.AdminIdField.Equals(value) != true)) {
                    this.AdminIdField = value;
                    this.RaisePropertyChanged("AdminId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trainer", Namespace="http://schemas.datacontract.org/2004/07/FitnessClub.DomainService.Models")]
    [System.SerializableAttribute()]
    public partial class Trainer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrainerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrainerId {
            get {
                return this.TrainerIdField;
            }
            set {
                if ((this.TrainerIdField.Equals(value) != true)) {
                    this.TrainerIdField = value;
                    this.RaisePropertyChanged("TrainerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrainerSchedule", Namespace="http://schemas.datacontract.org/2004/07/FitnessClub.DomainService.Models")]
    [System.SerializableAttribute()]
    public partial class TrainerSchedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan FromTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ToTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrainerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan FromTime {
            get {
                return this.FromTimeField;
            }
            set {
                if ((this.FromTimeField.Equals(value) != true)) {
                    this.FromTimeField = value;
                    this.RaisePropertyChanged("FromTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ToTime {
            get {
                return this.ToTimeField;
            }
            set {
                if ((this.ToTimeField.Equals(value) != true)) {
                    this.ToTimeField = value;
                    this.RaisePropertyChanged("ToTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrainerId {
            get {
                return this.TrainerIdField;
            }
            set {
                if ((this.TrainerIdField.Equals(value) != true)) {
                    this.TrainerIdField = value;
                    this.RaisePropertyChanged("TrainerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/FitnessClub.DomainService.Models")]
    [System.SerializableAttribute()]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/FitnessClub.DomainService.Models")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxParticipantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RepeatableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrainerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((this.FromDateField.Equals(value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxParticipants {
            get {
                return this.MaxParticipantsField;
            }
            set {
                if ((this.MaxParticipantsField.Equals(value) != true)) {
                    this.MaxParticipantsField = value;
                    this.RaisePropertyChanged("MaxParticipants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((this.PeriodField.Equals(value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Repeatable {
            get {
                return this.RepeatableField;
            }
            set {
                if ((this.RepeatableField.Equals(value) != true)) {
                    this.RepeatableField = value;
                    this.RaisePropertyChanged("Repeatable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrainerId {
            get {
                return this.TrainerIdField;
            }
            set {
                if ((this.TrainerIdField.Equals(value) != true)) {
                    this.TrainerIdField = value;
                    this.RaisePropertyChanged("TrainerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://schemas.datacontract.org/2004/07/FitnessClub.DomainService.Models")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedAt {
            get {
                return this.UpdatedAtField;
            }
            set {
                if ((this.UpdatedAtField.Equals(value) != true)) {
                    this.UpdatedAtField = value;
                    this.RaisePropertyChanged("UpdatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DbServiceRef.IDatabaseService")]
    public interface IDatabaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddCredential", ReplyAction="http://tempuri.org/IDatabaseService/AddCredentialResponse")]
        bool AddCredential(FitnessClubClient.DbServiceRef.Credential cred);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddCredential", ReplyAction="http://tempuri.org/IDatabaseService/AddCredentialResponse")]
        System.Threading.Tasks.Task<bool> AddCredentialAsync(FitnessClubClient.DbServiceRef.Credential cred);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetCredential", ReplyAction="http://tempuri.org/IDatabaseService/GetCredentialResponse")]
        FitnessClubClient.DbServiceRef.Credential GetCredential(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetCredential", ReplyAction="http://tempuri.org/IDatabaseService/GetCredentialResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Credential> GetCredentialAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateCredential", ReplyAction="http://tempuri.org/IDatabaseService/UpdateCredentialResponse")]
        bool UpdateCredential(FitnessClubClient.DbServiceRef.Credential cred);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateCredential", ReplyAction="http://tempuri.org/IDatabaseService/UpdateCredentialResponse")]
        System.Threading.Tasks.Task<bool> UpdateCredentialAsync(FitnessClubClient.DbServiceRef.Credential cred);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteCredential", ReplyAction="http://tempuri.org/IDatabaseService/DeleteCredentialResponse")]
        bool DeleteCredential(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteCredential", ReplyAction="http://tempuri.org/IDatabaseService/DeleteCredentialResponse")]
        System.Threading.Tasks.Task<bool> DeleteCredentialAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddUser", ReplyAction="http://tempuri.org/IDatabaseService/AddUserResponse")]
        bool AddUser(FitnessClubClient.DbServiceRef.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddUser", ReplyAction="http://tempuri.org/IDatabaseService/AddUserResponse")]
        System.Threading.Tasks.Task<bool> AddUserAsync(FitnessClubClient.DbServiceRef.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetUser", ReplyAction="http://tempuri.org/IDatabaseService/GetUserResponse")]
        FitnessClubClient.DbServiceRef.User GetUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetUser", ReplyAction="http://tempuri.org/IDatabaseService/GetUserResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.User> GetUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetAllUsers", ReplyAction="http://tempuri.org/IDatabaseService/GetAllUsersResponse")]
        FitnessClubClient.DbServiceRef.User[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetAllUsers", ReplyAction="http://tempuri.org/IDatabaseService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.User[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateUser", ReplyAction="http://tempuri.org/IDatabaseService/UpdateUserResponse")]
        bool UpdateUser(FitnessClubClient.DbServiceRef.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateUser", ReplyAction="http://tempuri.org/IDatabaseService/UpdateUserResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAsync(FitnessClubClient.DbServiceRef.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteUser", ReplyAction="http://tempuri.org/IDatabaseService/DeleteUserResponse")]
        bool DeleteUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteUser", ReplyAction="http://tempuri.org/IDatabaseService/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddAdmin", ReplyAction="http://tempuri.org/IDatabaseService/AddAdminResponse")]
        bool AddAdmin(FitnessClubClient.DbServiceRef.Admin admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddAdmin", ReplyAction="http://tempuri.org/IDatabaseService/AddAdminResponse")]
        System.Threading.Tasks.Task<bool> AddAdminAsync(FitnessClubClient.DbServiceRef.Admin admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetAdmin", ReplyAction="http://tempuri.org/IDatabaseService/GetAdminResponse")]
        FitnessClubClient.DbServiceRef.Admin GetAdmin(int adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetAdmin", ReplyAction="http://tempuri.org/IDatabaseService/GetAdminResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Admin> GetAdminAsync(int adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetAllAdmins", ReplyAction="http://tempuri.org/IDatabaseService/GetAllAdminsResponse")]
        FitnessClubClient.DbServiceRef.Admin[] GetAllAdmins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetAllAdmins", ReplyAction="http://tempuri.org/IDatabaseService/GetAllAdminsResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Admin[]> GetAllAdminsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateAdmin", ReplyAction="http://tempuri.org/IDatabaseService/UpdateAdminResponse")]
        bool UpdateAdmin(FitnessClubClient.DbServiceRef.Admin admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateAdmin", ReplyAction="http://tempuri.org/IDatabaseService/UpdateAdminResponse")]
        System.Threading.Tasks.Task<bool> UpdateAdminAsync(FitnessClubClient.DbServiceRef.Admin admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteAdmin", ReplyAction="http://tempuri.org/IDatabaseService/DeleteAdminResponse")]
        bool DeleteAdmin(int adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteAdmin", ReplyAction="http://tempuri.org/IDatabaseService/DeleteAdminResponse")]
        System.Threading.Tasks.Task<bool> DeleteAdminAsync(int adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddTrainer", ReplyAction="http://tempuri.org/IDatabaseService/AddTrainerResponse")]
        bool AddTrainer(FitnessClubClient.DbServiceRef.Trainer trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddTrainer", ReplyAction="http://tempuri.org/IDatabaseService/AddTrainerResponse")]
        System.Threading.Tasks.Task<bool> AddTrainerAsync(FitnessClubClient.DbServiceRef.Trainer trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetTrainer", ReplyAction="http://tempuri.org/IDatabaseService/GetTrainerResponse")]
        FitnessClubClient.DbServiceRef.Trainer GetTrainer(int trainerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetTrainer", ReplyAction="http://tempuri.org/IDatabaseService/GetTrainerResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Trainer> GetTrainerAsync(int trainerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetAllTrainers", ReplyAction="http://tempuri.org/IDatabaseService/GetAllTrainersResponse")]
        FitnessClubClient.DbServiceRef.Trainer[] GetAllTrainers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetAllTrainers", ReplyAction="http://tempuri.org/IDatabaseService/GetAllTrainersResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Trainer[]> GetAllTrainersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateTrainer", ReplyAction="http://tempuri.org/IDatabaseService/UpdateTrainerResponse")]
        bool UpdateTrainer(FitnessClubClient.DbServiceRef.Trainer trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateTrainer", ReplyAction="http://tempuri.org/IDatabaseService/UpdateTrainerResponse")]
        System.Threading.Tasks.Task<bool> UpdateTrainerAsync(FitnessClubClient.DbServiceRef.Trainer trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteTrainer", ReplyAction="http://tempuri.org/IDatabaseService/DeleteTrainerResponse")]
        bool DeleteTrainer(int trainerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteTrainer", ReplyAction="http://tempuri.org/IDatabaseService/DeleteTrainerResponse")]
        System.Threading.Tasks.Task<bool> DeleteTrainerAsync(int trainerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddSchedule", ReplyAction="http://tempuri.org/IDatabaseService/AddScheduleResponse")]
        bool AddSchedule(FitnessClubClient.DbServiceRef.TrainerSchedule schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddSchedule", ReplyAction="http://tempuri.org/IDatabaseService/AddScheduleResponse")]
        System.Threading.Tasks.Task<bool> AddScheduleAsync(FitnessClubClient.DbServiceRef.TrainerSchedule schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetSchedulesByTrainer", ReplyAction="http://tempuri.org/IDatabaseService/GetSchedulesByTrainerResponse")]
        FitnessClubClient.DbServiceRef.TrainerSchedule[] GetSchedulesByTrainer(int trainerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetSchedulesByTrainer", ReplyAction="http://tempuri.org/IDatabaseService/GetSchedulesByTrainerResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.TrainerSchedule[]> GetSchedulesByTrainerAsync(int trainerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateSchedule", ReplyAction="http://tempuri.org/IDatabaseService/UpdateScheduleResponse")]
        bool UpdateSchedule(FitnessClubClient.DbServiceRef.TrainerSchedule schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateSchedule", ReplyAction="http://tempuri.org/IDatabaseService/UpdateScheduleResponse")]
        System.Threading.Tasks.Task<bool> UpdateScheduleAsync(FitnessClubClient.DbServiceRef.TrainerSchedule schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteSchedule", ReplyAction="http://tempuri.org/IDatabaseService/DeleteScheduleResponse")]
        bool DeleteSchedule(int scheduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteSchedule", ReplyAction="http://tempuri.org/IDatabaseService/DeleteScheduleResponse")]
        System.Threading.Tasks.Task<bool> DeleteScheduleAsync(int scheduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddService", ReplyAction="http://tempuri.org/IDatabaseService/AddServiceResponse")]
        bool AddService(FitnessClubClient.DbServiceRef.Service service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddService", ReplyAction="http://tempuri.org/IDatabaseService/AddServiceResponse")]
        System.Threading.Tasks.Task<bool> AddServiceAsync(FitnessClubClient.DbServiceRef.Service service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetService", ReplyAction="http://tempuri.org/IDatabaseService/GetServiceResponse")]
        FitnessClubClient.DbServiceRef.Service GetService(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetService", ReplyAction="http://tempuri.org/IDatabaseService/GetServiceResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Service> GetServiceAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetAllServices", ReplyAction="http://tempuri.org/IDatabaseService/GetAllServicesResponse")]
        FitnessClubClient.DbServiceRef.Service[] GetAllServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetAllServices", ReplyAction="http://tempuri.org/IDatabaseService/GetAllServicesResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Service[]> GetAllServicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateService", ReplyAction="http://tempuri.org/IDatabaseService/UpdateServiceResponse")]
        bool UpdateService(FitnessClubClient.DbServiceRef.Service service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateService", ReplyAction="http://tempuri.org/IDatabaseService/UpdateServiceResponse")]
        System.Threading.Tasks.Task<bool> UpdateServiceAsync(FitnessClubClient.DbServiceRef.Service service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteService", ReplyAction="http://tempuri.org/IDatabaseService/DeleteServiceResponse")]
        bool DeleteService(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteService", ReplyAction="http://tempuri.org/IDatabaseService/DeleteServiceResponse")]
        System.Threading.Tasks.Task<bool> DeleteServiceAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddEvent", ReplyAction="http://tempuri.org/IDatabaseService/AddEventResponse")]
        bool AddEvent(FitnessClubClient.DbServiceRef.Event ev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddEvent", ReplyAction="http://tempuri.org/IDatabaseService/AddEventResponse")]
        System.Threading.Tasks.Task<bool> AddEventAsync(FitnessClubClient.DbServiceRef.Event ev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetEvent", ReplyAction="http://tempuri.org/IDatabaseService/GetEventResponse")]
        FitnessClubClient.DbServiceRef.Event GetEvent(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetEvent", ReplyAction="http://tempuri.org/IDatabaseService/GetEventResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Event> GetEventAsync(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetAllEvents", ReplyAction="http://tempuri.org/IDatabaseService/GetAllEventsResponse")]
        FitnessClubClient.DbServiceRef.Event[] GetAllEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetAllEvents", ReplyAction="http://tempuri.org/IDatabaseService/GetAllEventsResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Event[]> GetAllEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetEventsByDate", ReplyAction="http://tempuri.org/IDatabaseService/GetEventsByDateResponse")]
        FitnessClubClient.DbServiceRef.Event[] GetEventsByDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetEventsByDate", ReplyAction="http://tempuri.org/IDatabaseService/GetEventsByDateResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Event[]> GetEventsByDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateEvent", ReplyAction="http://tempuri.org/IDatabaseService/UpdateEventResponse")]
        bool UpdateEvent(FitnessClubClient.DbServiceRef.Event ev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateEvent", ReplyAction="http://tempuri.org/IDatabaseService/UpdateEventResponse")]
        System.Threading.Tasks.Task<bool> UpdateEventAsync(FitnessClubClient.DbServiceRef.Event ev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteEvent", ReplyAction="http://tempuri.org/IDatabaseService/DeleteEventResponse")]
        bool DeleteEvent(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteEvent", ReplyAction="http://tempuri.org/IDatabaseService/DeleteEventResponse")]
        System.Threading.Tasks.Task<bool> DeleteEventAsync(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddBooking", ReplyAction="http://tempuri.org/IDatabaseService/AddBookingResponse")]
        bool AddBooking(FitnessClubClient.DbServiceRef.Booking booking);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddBooking", ReplyAction="http://tempuri.org/IDatabaseService/AddBookingResponse")]
        System.Threading.Tasks.Task<bool> AddBookingAsync(FitnessClubClient.DbServiceRef.Booking booking);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetBooking", ReplyAction="http://tempuri.org/IDatabaseService/GetBookingResponse")]
        FitnessClubClient.DbServiceRef.Booking GetBooking(int bookingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetBooking", ReplyAction="http://tempuri.org/IDatabaseService/GetBookingResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Booking> GetBookingAsync(int bookingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetBookingsByUser", ReplyAction="http://tempuri.org/IDatabaseService/GetBookingsByUserResponse")]
        FitnessClubClient.DbServiceRef.Booking[] GetBookingsByUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetBookingsByUser", ReplyAction="http://tempuri.org/IDatabaseService/GetBookingsByUserResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Booking[]> GetBookingsByUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetBookingsByEvent", ReplyAction="http://tempuri.org/IDatabaseService/GetBookingsByEventResponse")]
        FitnessClubClient.DbServiceRef.Booking[] GetBookingsByEvent(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetBookingsByEvent", ReplyAction="http://tempuri.org/IDatabaseService/GetBookingsByEventResponse")]
        System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Booking[]> GetBookingsByEventAsync(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateBooking", ReplyAction="http://tempuri.org/IDatabaseService/UpdateBookingResponse")]
        bool UpdateBooking(FitnessClubClient.DbServiceRef.Booking booking);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/UpdateBooking", ReplyAction="http://tempuri.org/IDatabaseService/UpdateBookingResponse")]
        System.Threading.Tasks.Task<bool> UpdateBookingAsync(FitnessClubClient.DbServiceRef.Booking booking);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteBooking", ReplyAction="http://tempuri.org/IDatabaseService/DeleteBookingResponse")]
        bool DeleteBooking(int bookingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteBooking", ReplyAction="http://tempuri.org/IDatabaseService/DeleteBookingResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookingAsync(int bookingId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDatabaseServiceChannel : FitnessClubClient.DbServiceRef.IDatabaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseServiceClient : System.ServiceModel.ClientBase<FitnessClubClient.DbServiceRef.IDatabaseService>, FitnessClubClient.DbServiceRef.IDatabaseService {
        
        public DatabaseServiceClient() {
        }
        
        public DatabaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddCredential(FitnessClubClient.DbServiceRef.Credential cred) {
            return base.Channel.AddCredential(cred);
        }
        
        public System.Threading.Tasks.Task<bool> AddCredentialAsync(FitnessClubClient.DbServiceRef.Credential cred) {
            return base.Channel.AddCredentialAsync(cred);
        }
        
        public FitnessClubClient.DbServiceRef.Credential GetCredential(string login) {
            return base.Channel.GetCredential(login);
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Credential> GetCredentialAsync(string login) {
            return base.Channel.GetCredentialAsync(login);
        }
        
        public bool UpdateCredential(FitnessClubClient.DbServiceRef.Credential cred) {
            return base.Channel.UpdateCredential(cred);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCredentialAsync(FitnessClubClient.DbServiceRef.Credential cred) {
            return base.Channel.UpdateCredentialAsync(cred);
        }
        
        public bool DeleteCredential(string login) {
            return base.Channel.DeleteCredential(login);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCredentialAsync(string login) {
            return base.Channel.DeleteCredentialAsync(login);
        }
        
        public bool AddUser(FitnessClubClient.DbServiceRef.User user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> AddUserAsync(FitnessClubClient.DbServiceRef.User user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public FitnessClubClient.DbServiceRef.User GetUser(string username) {
            return base.Channel.GetUser(username);
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.User> GetUserAsync(string username) {
            return base.Channel.GetUserAsync(username);
        }
        
        public FitnessClubClient.DbServiceRef.User[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.User[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public bool UpdateUser(FitnessClubClient.DbServiceRef.User user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAsync(FitnessClubClient.DbServiceRef.User user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public bool DeleteUser(string username) {
            return base.Channel.DeleteUser(username);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(string username) {
            return base.Channel.DeleteUserAsync(username);
        }
        
        public bool AddAdmin(FitnessClubClient.DbServiceRef.Admin admin) {
            return base.Channel.AddAdmin(admin);
        }
        
        public System.Threading.Tasks.Task<bool> AddAdminAsync(FitnessClubClient.DbServiceRef.Admin admin) {
            return base.Channel.AddAdminAsync(admin);
        }
        
        public FitnessClubClient.DbServiceRef.Admin GetAdmin(int adminId) {
            return base.Channel.GetAdmin(adminId);
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Admin> GetAdminAsync(int adminId) {
            return base.Channel.GetAdminAsync(adminId);
        }
        
        public FitnessClubClient.DbServiceRef.Admin[] GetAllAdmins() {
            return base.Channel.GetAllAdmins();
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Admin[]> GetAllAdminsAsync() {
            return base.Channel.GetAllAdminsAsync();
        }
        
        public bool UpdateAdmin(FitnessClubClient.DbServiceRef.Admin admin) {
            return base.Channel.UpdateAdmin(admin);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAdminAsync(FitnessClubClient.DbServiceRef.Admin admin) {
            return base.Channel.UpdateAdminAsync(admin);
        }
        
        public bool DeleteAdmin(int adminId) {
            return base.Channel.DeleteAdmin(adminId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAdminAsync(int adminId) {
            return base.Channel.DeleteAdminAsync(adminId);
        }
        
        public bool AddTrainer(FitnessClubClient.DbServiceRef.Trainer trainer) {
            return base.Channel.AddTrainer(trainer);
        }
        
        public System.Threading.Tasks.Task<bool> AddTrainerAsync(FitnessClubClient.DbServiceRef.Trainer trainer) {
            return base.Channel.AddTrainerAsync(trainer);
        }
        
        public FitnessClubClient.DbServiceRef.Trainer GetTrainer(int trainerId) {
            return base.Channel.GetTrainer(trainerId);
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Trainer> GetTrainerAsync(int trainerId) {
            return base.Channel.GetTrainerAsync(trainerId);
        }
        
        public FitnessClubClient.DbServiceRef.Trainer[] GetAllTrainers() {
            return base.Channel.GetAllTrainers();
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Trainer[]> GetAllTrainersAsync() {
            return base.Channel.GetAllTrainersAsync();
        }
        
        public bool UpdateTrainer(FitnessClubClient.DbServiceRef.Trainer trainer) {
            return base.Channel.UpdateTrainer(trainer);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateTrainerAsync(FitnessClubClient.DbServiceRef.Trainer trainer) {
            return base.Channel.UpdateTrainerAsync(trainer);
        }
        
        public bool DeleteTrainer(int trainerId) {
            return base.Channel.DeleteTrainer(trainerId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTrainerAsync(int trainerId) {
            return base.Channel.DeleteTrainerAsync(trainerId);
        }
        
        public bool AddSchedule(FitnessClubClient.DbServiceRef.TrainerSchedule schedule) {
            return base.Channel.AddSchedule(schedule);
        }
        
        public System.Threading.Tasks.Task<bool> AddScheduleAsync(FitnessClubClient.DbServiceRef.TrainerSchedule schedule) {
            return base.Channel.AddScheduleAsync(schedule);
        }
        
        public FitnessClubClient.DbServiceRef.TrainerSchedule[] GetSchedulesByTrainer(int trainerId) {
            return base.Channel.GetSchedulesByTrainer(trainerId);
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.TrainerSchedule[]> GetSchedulesByTrainerAsync(int trainerId) {
            return base.Channel.GetSchedulesByTrainerAsync(trainerId);
        }
        
        public bool UpdateSchedule(FitnessClubClient.DbServiceRef.TrainerSchedule schedule) {
            return base.Channel.UpdateSchedule(schedule);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateScheduleAsync(FitnessClubClient.DbServiceRef.TrainerSchedule schedule) {
            return base.Channel.UpdateScheduleAsync(schedule);
        }
        
        public bool DeleteSchedule(int scheduleId) {
            return base.Channel.DeleteSchedule(scheduleId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteScheduleAsync(int scheduleId) {
            return base.Channel.DeleteScheduleAsync(scheduleId);
        }
        
        public bool AddService(FitnessClubClient.DbServiceRef.Service service) {
            return base.Channel.AddService(service);
        }
        
        public System.Threading.Tasks.Task<bool> AddServiceAsync(FitnessClubClient.DbServiceRef.Service service) {
            return base.Channel.AddServiceAsync(service);
        }
        
        public FitnessClubClient.DbServiceRef.Service GetService(string name) {
            return base.Channel.GetService(name);
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Service> GetServiceAsync(string name) {
            return base.Channel.GetServiceAsync(name);
        }
        
        public FitnessClubClient.DbServiceRef.Service[] GetAllServices() {
            return base.Channel.GetAllServices();
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Service[]> GetAllServicesAsync() {
            return base.Channel.GetAllServicesAsync();
        }
        
        public bool UpdateService(FitnessClubClient.DbServiceRef.Service service) {
            return base.Channel.UpdateService(service);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateServiceAsync(FitnessClubClient.DbServiceRef.Service service) {
            return base.Channel.UpdateServiceAsync(service);
        }
        
        public bool DeleteService(string name) {
            return base.Channel.DeleteService(name);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteServiceAsync(string name) {
            return base.Channel.DeleteServiceAsync(name);
        }
        
        public bool AddEvent(FitnessClubClient.DbServiceRef.Event ev) {
            return base.Channel.AddEvent(ev);
        }
        
        public System.Threading.Tasks.Task<bool> AddEventAsync(FitnessClubClient.DbServiceRef.Event ev) {
            return base.Channel.AddEventAsync(ev);
        }
        
        public FitnessClubClient.DbServiceRef.Event GetEvent(int eventId) {
            return base.Channel.GetEvent(eventId);
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Event> GetEventAsync(int eventId) {
            return base.Channel.GetEventAsync(eventId);
        }
        
        public FitnessClubClient.DbServiceRef.Event[] GetAllEvents() {
            return base.Channel.GetAllEvents();
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Event[]> GetAllEventsAsync() {
            return base.Channel.GetAllEventsAsync();
        }
        
        public FitnessClubClient.DbServiceRef.Event[] GetEventsByDate(System.DateTime date) {
            return base.Channel.GetEventsByDate(date);
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Event[]> GetEventsByDateAsync(System.DateTime date) {
            return base.Channel.GetEventsByDateAsync(date);
        }
        
        public bool UpdateEvent(FitnessClubClient.DbServiceRef.Event ev) {
            return base.Channel.UpdateEvent(ev);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateEventAsync(FitnessClubClient.DbServiceRef.Event ev) {
            return base.Channel.UpdateEventAsync(ev);
        }
        
        public bool DeleteEvent(int eventId) {
            return base.Channel.DeleteEvent(eventId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEventAsync(int eventId) {
            return base.Channel.DeleteEventAsync(eventId);
        }
        
        public bool AddBooking(FitnessClubClient.DbServiceRef.Booking booking) {
            return base.Channel.AddBooking(booking);
        }
        
        public System.Threading.Tasks.Task<bool> AddBookingAsync(FitnessClubClient.DbServiceRef.Booking booking) {
            return base.Channel.AddBookingAsync(booking);
        }
        
        public FitnessClubClient.DbServiceRef.Booking GetBooking(int bookingId) {
            return base.Channel.GetBooking(bookingId);
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Booking> GetBookingAsync(int bookingId) {
            return base.Channel.GetBookingAsync(bookingId);
        }
        
        public FitnessClubClient.DbServiceRef.Booking[] GetBookingsByUser(string username) {
            return base.Channel.GetBookingsByUser(username);
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Booking[]> GetBookingsByUserAsync(string username) {
            return base.Channel.GetBookingsByUserAsync(username);
        }
        
        public FitnessClubClient.DbServiceRef.Booking[] GetBookingsByEvent(int eventId) {
            return base.Channel.GetBookingsByEvent(eventId);
        }
        
        public System.Threading.Tasks.Task<FitnessClubClient.DbServiceRef.Booking[]> GetBookingsByEventAsync(int eventId) {
            return base.Channel.GetBookingsByEventAsync(eventId);
        }
        
        public bool UpdateBooking(FitnessClubClient.DbServiceRef.Booking booking) {
            return base.Channel.UpdateBooking(booking);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateBookingAsync(FitnessClubClient.DbServiceRef.Booking booking) {
            return base.Channel.UpdateBookingAsync(booking);
        }
        
        public bool DeleteBooking(int bookingId) {
            return base.Channel.DeleteBooking(bookingId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookingAsync(int bookingId) {
            return base.Channel.DeleteBookingAsync(bookingId);
        }
    }
}
